# Generated by Django 3.0.7 on 2020-12-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdityaMuley', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
